version: "2"
services:
  app:
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
        - "MYSQL_DATABASE=homestead"
        - "MYSQL_USER=homestead"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_ROOT_PASSWORD=secret"
        - "REDIS_HOST=cache"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    build:
        context: ./config/docker/
        dockerfile: app.dockerfile
    links:
      - cache
      - database
  composer:
    restart: 'no'
    image: composer/composer
    volumes:
      - ./:/app
    command: install
  web:
    build:
      context: ./config/docker/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - "8080:80"
    links:
      - app

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

  node:
    restart: 'no'
    build:
      context: ./
      dockerfile: config/docker/node.dockerfile
    volumes:
      - ./:/app

  echo-server:
    volumes:
      - ./:/app
    build:
      context: ./config/docker
      dockerfile: echo.dockerfile
    links:
      - cache

  cache:
      image: redis:3.0-alpine

volumes:
  dbdata:
