openapi: 3.0.0
info:
  description: "This swagger documents the runners api."
  version: "v2.0.0-rc.1.2"
  title: "Runners"
tags:
- name: "me"
  description: "Routes related to the authenticated user"
- name: "users"
  description: "Users resource"
- name: "schedules"
  description: "Schedules resource"
- name: "runs"
  description: "Runs resource"
- name: "runners"
  description: "Runners resource (subscriptions)"
- name: "waypoints"
  description: "Waypoints resource"
- name: "cars"
  description: "Cars resource"
- name: "groups"
  description: "Groups resource"
schemes:
- "https"
- "http"
paths:
  /me:
    get:
      tags:
      - "me"
      summary: "Get the current authenticated user"
      description: "Check the bearer authentication, and return the current User model"
      responses:
        '200':    # status code
          description: User model serialized to JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/User"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /me/workinghours:
    get:
      tags:
      - "me"
      summary: "Get the current authenticated user schedules"
      responses:
        '200':
          description: "Schedule model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Schedule"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /me/runs:
    get:
      tags:
      - "me"
      summary: "Get the current authenticated user runs"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Run"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /users:
    get:
      tags:
      - "users"
      summary: "Get all the users"
      responses:
        '200':    # status code
          description: "User model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/User"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /users/{user}:
    get:
      tags:
      - "users"
      summary: "Get specific user by his ID"
      parameters:
        - name: user
          in: path
          required: true
          description: "The id of the user"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "User model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/User"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /schedules:
    get:
      tags:
      - "schedules"
      summary: "Get all the schedules"
      responses:
        '200':    # status code
          description: "Schedule model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Schedule"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /runs:
    get:
      tags:
      - "runs"
      summary: "Get all the runs"
      parameters:
        - name: finished
          in: query
          required: false
          description: "Bolean if you want just finished runs '?finished=true'"
          schema:
            type : string
            minimum: 1
        - name: status
          in: query
          required: false
          description: "Name of the status you want to filter the request"
          schema:
            type : string
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Run"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /runs/{run}:
    get:
      tags:
      - "runs"
      summary: "Get specific run by his ID"
      parameters:
        - name: run
          in: path
          required: true
          description: "The id of the run"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Run"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /runs/{run}/start:
    post:
      tags:
      - "runs"
      summary: "Start a specific run by his ID"
      parameters:
        - name: run
          in: path
          required: true
          description: "The id of the run"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Run"
        '405':
          description: "The run can not be started"
        '401':
          description: "Unauthorized"
  /runs/{run}/stop:
    post:
      tags:
      - "runs"
      summary: "Stop a specific run by his ID"
      parameters:
        - name: run
          in: path
          required: true
          description: "The id of the run"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Run"
        '405':
          description: "The run can not be stopped"
        '401':
          description: "Unauthorized"
  /runs/{run}/runners:
    post:
      tags:
      - "runs"
      summary: "Sets the current authenticated user to the first empty subscription of the run."
      parameters:
        - name: run
          in: path
          required: true
          description: "The id of the run"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Runner"
        '405':
          description: "The current user cannot be attached to this run."
        '401':
          description: "Unauthorized"
  /runs/{run}/waypoints:
    get:
      tags:
      - "runs"
      summary: "Show the waypoints of this run."
      parameters:
        - name: run
          in: path
          required: true
          description: "The id of the run"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Waypoint model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Waypoint"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
  /runners/{runner}:
    get:
      tags:
      - "runners"
      summary: "Get specific run subscription by his ID"
      parameters:
        - name: runner
          in: path
          required: true
          description: "The id of the run subscription"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Runner"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
    patch:
      tags:
      - "runners"
      summary: "Update specific run subscription by his ID"
      parameters:
        - name: runner
          in: path
          required: true
          description: "The id of the run subscription"
          schema:
            type : integer
            minimum: 1
      responses:
        '200':    # status code
          description: "Run model serialized to JSON"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Runner"
        '405':
          description: "Method not allowed"
        '401':
          description: "Unauthorized"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: base64
security:
  - bearerAuth: []
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
      phone_number:
        type: "string"
      sex:
        type: "string"
      status:
        type: "string"
      image_profile:
        type: "string"
        description: "Link to the user profile picture."
  Schedule:
    type: "object"
    properties:
      start_at:
        type: "string"
      end_at:
        type: "string"
  Run:
    type: "object"
    properties:
      id:
        type: "integer"
      status:
        type: "string"
      title:
        type: "string"
      begin_at:
        type: "string"
      start_at:
        type: "string"
      end_at:
        type: "string"
      finished_at:
        type: "string"
      nb_passenger:
        type: "string"
      waypoints:
        type: "array"
        items:
          $ref: "#/definitions/Waypoint"
      runners:
        type: "array"
        items:
          $ref: "#/definitions/Runner"
  Waypoint:
    type: "object"
    properties:
      nickname:
        type: "string"
  Runner:
    type: "object"
    properties:
      id:
        type: "integer"
      user:
        type: "array"
        items:
          $ref: "#/definitions/User"
      vehicle_category:
        type: "array"
        items:
          $ref: "#/definitions/CarType"
      vehicle:
        type: "array"
        items:
          $ref: "#/definitions/Car"
  CarType:
    type: "object"
    properties:
      type:
        type: "string"
      description:
        type: "string"
  Car:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      plate_number:
        type: "string"
      nb_place:
        type: "integer"
      status:
        type: "string"
      user:
        type: "null"
      type:
        type: "array"
        items:
          $ref: "#/definitions/CarType"
      comments:
        type: "array"
        items:
          $ref: "#/definitions/Comment"
  Comment:
    type: "object"
    properties:
      id:
        type: "integer"
      content:
        type: "string"
      user:
        type: "array"
        items:
          $ref: "#/definitions/User"
      created_at:
        type: "string"