# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Runners API
  description: Application for the paleo
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /users:
    get:
      summary: User Types
      description:
        List all users
      tags:
        - Users
      responses:
        200:
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /users/me:
    get:
      summary: User Types
      description: "The authenticated user (Identified by the token)"
      tags:
        - Users
      responses:
        200:
          description: A user
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runs:
    post:
      summary:
      description:
      parameters:
        - name: name
          required: true
          in: body
          type: string
        - name: waypoints
          required: false
          type: array
          description: Array of waypoint NAMES ["Somewhere","Over","The","Rainbow"]. If a waypoint doesn'0t exist, it will be create
          items:
            type: string
        - name: subscriptions
          required: false
          description:
            Array of subscriptions.
            If provided with existing subscriptions, they will be updated.
            ["car":2,"user":5] or
            ["id":1, "car":2, "user":null]
            None of the fields are required. If nothing is put in a subscription this basicly tells the run it must have 2 convoys, but that is it
          type: array
          items:
            $ref: '#/definitions/RunSubscriptionInsert'
      responses:
        200:
          description: The newly created run
          schema:
            $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: User Types
      description:
        List all runs
      parameters:
        - name: status
          in: query
          description: "Allows to recover the runs according to their status such as : [reserved, finish, current]. Example : /runs?status=finish,current"
          required: false
          type: string

        - name: sortBy
          in: query
          description: "Allows to order the runs directly from query. Multiple fields and order can be supplied (seperated by ','). Example: /runs?sortBy=planned_at DESC,status ASC"
          required: false
          type: string

        - name: between
          in: query
          description: "Allows querying between time periods. Comma seperated values. MAX 2 allowed /runs?between=2017-06-08,2017-06-09"
          required: false
          type: string

        - name: actif
          in: query
          required: false
          type: boolean
          description: "Filters run that are already gone and finished"

        - name: finished
          in: query
          required: false
          type: boolean
          default: false
          description: "Filters all the runs that are finished /runs?finished=true"
      tags:
        - Runs
      responses:
        200:
          description: An array of runs
          schema:
            type: array
            items:
              $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runs/{id}:
    get:
      summary: Run Types
      description:
        List all run
      parameters:
        - name: id
          in: path
          description: Unique identifier of the run
          required: true
          type: number
      tags:
        - Runs
      responses:
        200:
          description: An array of runs
          schema:
            type: array
            items:
              $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runs/{id}/start:
    post:
      summary: Start the run
      description:
        Start the run only if all runners are ready and have vehicles.
      parameters:
        - name: id
          in: path
          description: Unique identifier of the runner
          required: true
          type: number
      tags:
        - Runs
        - Users
        - Geocoders
        - Vehicles
      responses:
        200:
          description: Run object with the start_at filled
          schema:
            type: array
            items:
              $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runs/{id}/stop:
    post:
      summary: Stop the run
      description:
        Indicates that the run has been completed. (filled end_at)
      parameters:
        - name: id
          in: path
          description: Unique identifier of the runner
          required: true
          type: number
      tags:
        - Runs
      responses:
        200:
          description: Run object with the start_at filled
          schema:
            type: array
            items:
              $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runners/{id}:
    patch:
      summary: Runners
      description: "Allow to edit / remove car or user linked to one run."
      parameters:
        - name: id
          in: path
          description: Unique identifier of the runner
          required: true
          type: number
        - name: runners
          in: body
          required: true
          schema:
            $ref: "#/definitions/Runners"
      tags:
        - Runs
      responses:
        200:
          description: An array of runs
          schema:
            type: array
            items:
              $ref: '#/definitions/Run'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /runners/{id}/vehicles:
    get:
      summary: Vehicles for a runner
      description:
        List all vehicles link or not to a runner (look parameters)
      parameters:
        - name: id
          in: path
          description: Unique identifier of the runner
          required: true
          type: number

        - name: status
          in: query
          description: "Allows you to filter vehicles"
          required: true
          type: string
          enum:
           - free
           - taken
      tags:
       - Runners
      responses:
        200:
          description: An array of vehicles
          schema:
            type: array
            items:
              $ref: '#/definitions/Vehicle'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /cars:
    post:
      summary: Create a new car
      description:  Create a car. You can easily create a car with only a car_type, if needed.
      tags:
        - Vehicles
      parameters:
        - name: plate_number
          in: body
          description: THe plate number of the car. A validation error will be thrown if plate number alredy exist in db.
          required: false
          type: string
        - name: brand
          in: body
          required: false
          description: Brand of the car
          type: string
        - name: model
          in: body
          required: false
          description: Model of the car
          type: string
        - name: car_type
          in: body
          required: true
          type: number
          description: Car type identifier. Only required field.
        - name: nb_place
          in: body
          required: false
          description: Number of seats available in car. If nothing is provided, will take number of seats of car.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Vehicle'

    get:
      summary: Vehicles Types
      description:
        List all vehicles
      parameters:
        - name: status
          in: query
          description: "Allows you to retrieve a list of vehicles according to their status : [taken, free]. /vehicles?status=taken"
          required: false
          type: string
        - name: type
          in: query
          description: "Allows you to retrieve a list of vehicles according to type such as : [Vito, Limo]. /vehicles?staus=taken&type=Limo"
          required: false
          type: string
        - name: include
          in: query
          description: "Add user object if the vehicle is taken : /vehicles?include=user"
          type: string
      tags:
        - Vehicles
      responses:
        200:
          description: An array of vehicles
          schema:
            type: array
            items:
              $ref: '#/definitions/Vehicle'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /vehicles:
    get:
      summary: Vehicles Types
      description:
        List all vehicles
      parameters:
        - name: status
          in: query
          description: "Allows you to retrieve a list of vehicles according to their status : [taken, free]. /vehicles?status=taken"
          required: false
          type: string
        - name: type
          in: query
          description: "Allows you to retrieve a list of vehicles according to type such as : [Vito, Limo]. /vehicles?staus=taken&type=Limo"
          required: false
          type: string
        - name: include
          in: query
          description: "Add user object if the vehicle is taken : /vehicles?include=user"
          type: string
      tags:
        - Vehicles
      responses:
        200:
          description: An array of vehicles
          schema:
            type: array
            items:
              $ref: '#/definitions/Vehicle'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /status/vehicles:
    get:
      summary: Vehicle Status (DEPRECATED)
      description:
        List all vehicles with them status
        This method is use in actual runners mobile application but you should remove it and use /vehicles instead
      tags:
       - Status
      responses:
        200:
          description: An array of status of vehicles
          schema:
            type: array
            items:
              $ref: '#/definitions/VehicleStatus'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /groups:
    get:
      summary: Return all the groups
      description: Return all the groups
      tags:
        - Groups
      responses:
        200:
          description: An array of groups
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /groups/{id}/:
    patch:
      summary: Update a group
      description: Update a group data, and it's associated user
      parameters:
        - name: id
          in: path
          description: Unique identifier of the run
          required: true
          type: number
        - name: user
          in: body
          description:
            ID of user. Changes the group of the user to the group {id}
          required: false
          schema:
            type: string
      tags:
        - Groups
      responses:
        200:
          description: The modified group
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /schedules:
    get:
      summary: Returns all the schdules
      description: Allows you to get the schedule of everybody
      parameters:
        - name: between
          in: query
          description: "Allows querying between time periods. Comma seperated values. MAX 2 allowed /schedules?between=2017-06-08,2017-06-09"
          required: false
          type: string
      responses:
        200:
          description: An array of schdules
          schema:
            type: array
            items:
              $ref: '#/definitions/Schedule'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Schedule:
    type: object
    properties:
      id:
        description: Unique identifier (PK)
        type: integer
      start_time:
        description: start of schedule (date time)
        type: string
        format: date-time
      end_time:
        description: end of schedule (date time)
        type: string
        format: date-time
  Group:
    type: object
    properties:
      id:
        description: Unique identifier (PK)
        type: integer
      color:
        description: Color the ui should use to display the group (color is hex format)
        type: string
      name:
        description: Name of the group
        type: string
  Setting:
    type: object
    properties:
      key:
        description: Unique identifier
        type: string
      value:
        description: Value of the setting
        type: string
  Waypoint:
    type: object
    properties:
      id:
        description: Unique identifier (PK)
        type: integer
      name:
        description: Short name of the waypoint (used by coordinators)
        type: string
      geocoder:
        $ref: '#/definitions/Geocoder'

  Vehicle:
    type: object
    properties:
      id:
        description: Unique identifier (PK)
        type: integer
      name:
        description: Name of the car
        type: string
      type:
        $ref: '#/definitions/VehicleType'
      plate_number:
        description: Car plate number
        type: string
      nb_place:
        description: Number of places available in the car (driver's place is excluded)
        type: integer
      # user:
      #   $ref: '#/definitions/User'
  User:
    type: object
    properties:
      id:
        description: Unique identifier (PK)
        type: integer
      firstname:
        description: Driver's first name
        type: string
      lastname:
        description: Driver's last name
        type: string
      phone_number:
        description: Driver's phone number
        type: string

  VehicleType:
    type: object
    properties:
      type:
        type: string
      description:
        type: string

  VehicleStatus:
    type: object
    properties:
      vehicle:
        $ref: '#/definitions/Vehicle'
      status:
        type: string
        description: "Type : free, taken"
      user:
        $ref: '#/definitions/User'

  Run:
    type: object
    properties:
      id:
        description: Identifiant unique
        type: integer
      title:
        type: string
      waypoints:
        type: array
        description: "Lists the steps in geographical ways in order to complete the run"
        items:
          $ref: '#/definitions/Waypoint'
      begin_date:
        type: string
        format: date-time
        description: When the race should start
      start_at:
        type: string
        description: When the race begins (action of the runner)
        format: date-time
      end_at:
        description: When the race ends
        type: string
        format: date-time
      status:
        type: string
        description: "Run status: free, incomplete, ..."
      runners:
        type: array
        description: "The table of runners allows us to define the number of runners and the vehicles taken by the runner"
        items:
          $ref: '#/definitions/Runners'


  Runners:
    type: object
    properties:
      id:
        type: string
      user:
        $ref: '#/definitions/User'
      vehicle_category:
        $ref: '#/definitions/VehicleType'
      vehicle:
        $ref: '#/definitions/Vehicle'

  RunSubscriptionInsert:
    ẗype: object
    properties:
      id:
        type: number
        description: Unique identifier (ID)
      car:
        type: number
        description: car id
      user:
        type: number
        description: user id
      car_type:
        type: number
        description: car type id
# Google Map API
  Geocoder:
    type: object
    properties:
      address_components:
        type: array
        description:
          An array of GeocoderAddressComponents
        items:
          $ref: '#/definitions/GeocoderAddressComponent'
      formatted_address:
        type: string
        description:
          A string containing the human-readable address of this location.
        items:
          type: string
      geometry:
        $ref: '#/definitions/GeocoderGeometry'
      place_id:
        type: string
      types:
        type: array
        items:
              type: string

  GeocoderAddressComponent:
    type: object
    properties:
      long_name:
        type: string
        description: The full text of the address component
      short_name:
        type: string
        description: The abbreviated, short text of the given address component
      types:
        type: array
        description: An array of strings denoting the type of this address component. A list of valid types can be found here https://developers.google.com/maps/documentation/geocoding/intro?hl=fr#Types
        items:
         type: string

  GeocoderGeometry:
    type: object
    properties:
      location:
        type: object
        properties:
          lat:
            type: string
          lng:
            type: string
      location_type:
        type: string
        items:
          type: string
      viewport:
        type: object
        properties:
          northeast:
            type: object
            properties:
              lat:
                type: string
              lng:
                type: string
          southwest:
            type: object
            properties:
              lat:
                type: string
              lng:
                type: string

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      ui_message:
        type: string
